import type { NextPage } from "next";
import Head from "next/head";
import Actions from "../components/Actions";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className={styles.grid}>
        <Actions />
      </div>
    </>
  );
};

export default Home;
