import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Actions from "../components/Actions";
import Header from "../components/Header";
import { I18nContext } from "../context/I18nContext";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const _ = React.useContext(I18nContext);

  return (
    <>
      <Head>
        <title>{_("APP_TITLE")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Actions />
    </>
  );
};

export default Home;
